### ISSUE TITLE
pnpm dlx nuxi typecheck

### ISSUE THREAD

**Issue by chang-ryan** [07akioni/naive-ui-nuxt-demo#21]
Hello! I've cloned the repo and have simply done `pnpm install`

I wanted to see if `nuxi typecheck` works with this demo. Is it working for any of the maintainers? @DannyFeliz @07akioni

**Comment by chang-ryan** [comment]
this is the error i'm getting

```bash
Projects/naive-ui-nuxt-demo [ pnpm dlx nuxi typecheck                                                         main ] 8:33 PM

[8:33:54 PM]  ERROR  Cannot find module @nuxt/kit imported from file:///Users/admin/Projects/naive-ui-nuxt-demo, file:///Users/admin/Projects/, file:///Users/admin/Projects/naive-ui-nuxt-demo/_index.js, file:///Users/admin/Projects/node_modules

  at _resolve (/Users/admin/Library/Caches/pnpm/dlx/xwvwkvxd5zeesozvkaiojf7at4/1903dd5a90d-93a2/node_modules/.pnpm/nuxi@3.12.0/node_modules/nuxi/dist/shared/nuxi.b4f7d829.mjs:7998:19)
  at resolveSync (/Users/admin/Library/Caches/pnpm/dlx/xwvwkvxd5zeesozvkaiojf7at4/1903dd5a90d-93a2/node_modules/.pnpm/nuxi@3.12.0/node_modules/nuxi/dist/shared/nuxi.b4f7d829.mjs:8007:10)
  at resolvePathSync (/Users/admin/Library/Caches/pnpm/dlx/xwvwkvxd5zeesozvkaiojf7at4/1903dd5a90d-93a2/node_modules/.pnpm/nuxi@3.12.0/node_modules/nuxi/dist/shared/nuxi.b4f7d829.mjs:8010:24)
  at resolvePath (/Users/admin/Library/Caches/pnpm/dlx/xwvwkvxd5zeesozvkaiojf7at4/1903dd5a90d-93a2/node_modules/.pnpm/nuxi@3.12.0/node_modules/nuxi/dist/shared/nuxi.b4f7d829.mjs:8014:28)
  at importModule (/Users/admin/Library/Caches/pnpm/dlx/xwvwkvxd5zeesozvkaiojf7at4/1903dd5a90d-93a2/node_modules/.pnpm/nuxi@3.12.0/node_modules/nuxi/dist/shared/nuxi.b4f7d829.mjs:8055:30)
  at loadKit (/Users/admin/Library/Caches/pnpm/dlx/xwvwkvxd5zeesozvkaiojf7at4/1903dd5a90d-93a2/node_modules/.pnpm/nuxi@3.12.0/node_modules/nuxi/dist/shared/nuxi.a5b1f4d1.mjs:2430:21)
  at async Object.run (/Users/admin/Library/Caches/pnpm/dlx/xwvwkvxd5zeesozvkaiojf7at4/1903dd5a90d-93a2/node_modules/.pnpm/nuxi@3.12.0/node_modules/nuxi/dist/chunks/typecheck.mjs:57:9)
  at async runCommand$1 (/Users/admin/Library/Caches/pnpm/dlx/xwvwkvxd5zeesozvkaiojf7at4/1903dd5a90d-93a2/node_modules/.pnpm/nuxi@3.12.0/node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1648:16)
  at async runCommand$1 (/Users/admin/Library/Caches/pnpm/dlx/xwvwkvxd5zeesozvkaiojf7at4/1903dd5a90d-93a2/node_modules/.pnpm/nuxi@3.12.0/node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1639:11)
  at async runMain$1 (/Users/admin/Library/Caches/pnpm/dlx/xwvwkvxd5zeesozvkaiojf7at4/1903dd5a90d-93a2/node_modules/.pnpm/nuxi@3.12.0/node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1777:7)



[8:33:54 PM]  ERROR  Cannot find module @nuxt/kit imported from file:///Users/admin/Projects/naive-ui-nuxt-demo, file:///Users/admin/Projects/, file:///Users/admin/Projects/naive-ui-nuxt-demo/_index.js, file:///Users/admin/Projects/node_modules
```
